## EXAM 1

**Q1** [5 pts] Consider two lists La and Lb of pairs, e.g.,:
```
La = [ ("DLL1", -0.68), ("BRCA2", 0.02), ("IGF2", 1.34), ("TNF", -1.87) ]
Lb = [ ("TRPV2", 12732), ("DLL1", 8342), ("BRCA2",6334), ("IGF2", 18342) ]
```

write a piece of code to perform the (inner) join of the two lists on the first element of the pairs. The result should be a new list Lc, such that:
```
Lc = [("DLL1", -0.68, 8342), ("BRCA2", 0.02, 6332), ("IGF2", 1.34, 18342)]```

In [3]:
from numpy.ma.extras import average

La = [ ("DLL1", -0.68), ("BRCA2", 0.02), ("IGF2", 1.34), ("TNF", -1.87) ]
Lb = [ ("TRPV2", 12732), ("DLL1", 8342), ("BRCA2",6334), ("IGF2", 18342) ]


In [12]:
#Smarter Version
dicta=dict(La)
dictb=dict(Lb)
key= set(dicta.keys()).intersection(set(dictb.keys()))
Lcc=[(ky,dicta.get(ky),dictb.get(ky) )for ky in key]
print(Lcc)

[('IGF2', 1.34, 18342), ('BRCA2', 0.02, 6334), ('DLL1', -0.68, 8342)]


In [5]:
dict_a={tuple[0]:tuple[1] for tuple in La}
dict_b={tuple[0]:tuple[1] for tuple in Lb}
keys= set(dict_a.keys()).intersection(set(dict_b.keys()))
Lc=[(key,dict_a.get(key),dict_b.get(key) )for key in keys]
print(Lc)

[('IGF2', 1.34, 18342), ('BRCA2', 0.02, 6334), ('DLL1', -0.68, 8342)]


Try the same question with left, right and full outer joins 
```
SELECT La.gene, La.value, Lb.value
FROM La
LEFT JOIN Lb ON La.gene = Lb.gene
```
```
SELECT Lb.gene, La.value, Lb.value
FROM La
RIGHT JOIN Lb ON La.gene = Lb.gene
```
```
SELECT La.gene,Lb.gene, La.value, Lb.value
FROM La
OUTER JOIN Lb ON La.gene = Lb.gene
```

#### LEFT JOIN RESULT
Lc = [("DLL1", -0.68, 8342),("BRCA2", 0.02, 6332),("IGF2", 1.34, 18342), ("TNF",-1.87, None)]

In [14]:
d_b=dict(Lb)
lj=[(gene,value, dict_b.get(gene, None)) for gene, value in La]
print(lj)


[('DLL1', -0.68, 8342), ('BRCA2', 0.02, 6334), ('IGF2', 1.34, 18342), ('TNF', -1.87, None)]


#### RIGHT JOIN RESULT
Lc = [("DLL1", -0.68, 8342),("BRCA2", 0.02, 6332),("IGF2", 1.34, 18342), ("TRPV2",None,12732)]

In [17]:
d_a=dict(La)
rj=[(gene,d_a.get(gene, None),value) for gene,value in Lb]
print(rj)

[('TRPV2', None, 12732), ('DLL1', -0.68, 8342), ('BRCA2', 0.02, 6334), ('IGF2', 1.34, 18342)]


#### FULL OUTER JOIN
Lc = [("DLL1", -0.68, 8342),("BRCA2", 0.02, 6332), ("IGF2", 1.34, 18342), ("TNF",-1.87, None), ("TRPV2",None,12732)]

In [18]:
a=dict(La)
b=dict(Lb)
keyss= set(a.keys()).union(set(b.keys()))
fj=[(ky,a.get(ky,None), b.get(ky,None)) for ky in keyss]
print(fj)


[('IGF2', 1.34, 18342), ('TRPV2', None, 12732), ('TNF', -1.87, None), ('BRCA2', 0.02, 6334), ('DLL1', -0.68, 8342)]


**Q2** [6 pts] The Python built-in function `int(string)` parses, if possible, an input string object into an integer object. Implement a **recursive** function `my_int(string)` that performs the same operation.

In [ ]:
##not resolved because it only makes sense with recursive implementation

**Q3** [5 pts] A comma separated files stores for each patient a series of measurements. Each patient may have a different number of reported measurements. An example of
the file follows:
```
Patient1, 23.4, 53.2, 6.3, 3.5
Patient2, 2.4, 44.6, 33.2, 14.5, 65.2
Patient3, 38.5, 56.7, 6.4
```
write a function `process_file(input_path, output_path)`. The function reads the file at input_path and writes into a new file at output_path a summary of the first in
the format:
```
PatientID, min_measurement, max_measurement, average_measurement
```

In [55]:
with open('inpt.txt', 'w') as f:
    li=['Patient1, 23.4, 53.2, 6.3, 3.5', 'Patient2, 2.4, 44.6, 33.2, 14.5, 65.2', 'Patient3, 38.5, 56.7, 6.4']
    f.writelines("\n".join(li))


def process_file(input_path:str, output_path:str):
    with open(input_path,"r") as file:
      with open(output_path,"w") as f:
        f.write("PatientID, Min, Max, Average\n")
        for line in file:
            line = line.strip().split(',')
            valu=list(map(float, line[1:]))
            aver=sum(valu)/len(valu)
            info=f'{line[0]}, {min(valu)}, {max(valu)}, {aver}\n'
            f.write(info)
    with open(output_path,"r") as f:
      return '\n'.join(f.readlines())

print(process_file("inpt.txt","output.txt"))

PatientID, Min, Max, Average

Patient1, 3.5, 53.2, 21.6

Patient2, 2.4, 65.2, 31.98

Patient3, 6.4, 56.7, 33.86666666666667



**Q4** [10 pts] 

A FIFO (first-in, first-out) is a data structure that allows two operations: `insert(elem)` and `get()`. 

Every time the insert is invoked a new element is inserted in the structure, while every time the get is invoked the “oldest” element in the structure is returned and removed from the list. Implement a class `FIFO`, with the following additions: 
- (a) the class is created empty; 
- (b) if the get method is invoked and no element is present in the structure, a `FIFOException` (to be also defined) is raised; 
- (c) a boolean method `has_next()` returns True if at least one element is still present in the structure; 
- (d) a `reset()` method restores the initial status (empty FIFO) by removing one by one all the elements by invoking the get() method.

In [56]:
class FIFIException(Exception):
    def __init__(self, msg):
        self.msg = msg
    def __str__(self):
        return self.msg

class FIFO:
    def __init__(self):
        self.queue =[]

    def insert(self, item):
        self.queue.append(item)

    def get(self):
        if len(self.queue) == 0:
            raise FIFOException("FIFO queue is empty")
        r=self.queue[0]
        del self.queue[0]
        return r
    def has_next(self):
        if len(self.queue) >=1:
            return True
        else:
            return False

    def reset(self):
        while len(self.queue) > 0:
            try:
                self.get()
            except FIFOException as e:
                print(e)


test_fifo = FIFO()
test_fifo.insert('A')
test_fifo.insert('B')
test_fifo.insert('C')
print(test_fifo.queue)
test_fifo.get()
print(test_fifo.queue)
test_fifo.reset()
print(test_fifo.queue)


['A', 'B', 'C']
['B', 'C']
[]


In [8]:
class FIFOException(Exception):
        pass
    
class FIFO:
    def __init__(self):
        self.inner_list = []
        
    def insert(self,elem):
        self.inner_list.append(elem)
        
    def get(self):
        
        if self.has_next():        
            result = self.inner_list[0]
            self.inner_list = self.inner_list[1:]
            return result
        else:
            raise FIFOException('be careful! empty list')
    
    def has_next(self):
        return len(self.inner_list)>0
    
    def reset(self):
        while True:
            if self.has_next():
                self.get()
            else:
                break

test_fifo = FIFO()
test_fifo.insert('A')
test_fifo.insert('B')
test_fifo.insert('C')
print(test_fifo.inner_list)
test_fifo.get()
print(test_fifo.inner_list)
test_fifo.reset()
print(test_fifo.inner_list)


['A', 'B', 'C']
['B', 'C']
[]


## Ex6
A list of triplets in the format (patient_id, SNP_id, trait), e.g., (P01,
rs206437, hypertension) , is used for a Genome-Wide Association Study. Write
a piece of software that prints, for each trait, the most associated SNP_id.

In [2]:
l = [
    ("P01", "rs206437", "hypertension"),
    ("P02", "s2",       "hypertension"),
    ("P03", "s2",       "hypertension"),
    ("P03", "rs206437", "hypertension"),
    ("P04", "rs206437", "hypertension"),
    ("P04", "rs206437", "brca"),
]

In [3]:
gwd={}
for p,snp,trait in l:
    if trait not in gwd:
        gwd[trait]={snp:1}
    elif snp not in gwd[trait]:
        gwd[trait].update({snp:1})
    else:
        gwd[trait][snp]+=1

frequent=[]
for trait,snp_dict in gwd.items():
    maax=max(list(snp_dict.values()))
    for snp,count in snp_dict.items():
        if count == maax:
            frequent.append(f'the most associated snp for {trait} is {snp}: {count}')






{'hypertension': {'rs206437': 3, 's2': 2}, 'brca': {'rs206437': 1}}

In [28]:
#alt1
do = {}
for patient,snp,trait in l:
    if trait not in do.keys():
        do[trait] = {}
        do[trait][snp] = 1
    else:
        if snp not in do[trait]:
            do[trait][snp] = 1
        else:
            do[trait][snp] += 1

#alt2
#do = {}
#for patient,snp,trait in l:
#    if trait in do.keys():
#        if snp in do[trait].keys():
#            do[trait][snp] += 1
#        else:
#            do[trait][snp] = 1
#    else:
#        do[trait] = {} ### inner dictionary
#        do[trait][snp] = 1
            
for trait in do:
    max_value_trait = max(do[trait].values())
    
    snp_with_max = [snp  for snp,value in do[trait].items() if value == max_value_trait ]
    
    print(f'For trait {trait}, the snp {snp_with_max} is the most associated/represented one, with {max_value_trait} occurrences\n')

For trait hypertension, the snp ['rs206437'] is the most associated/represented one, with 3 occurrences

For trait brca, the snp ['rs206437'] is the most associated/represented one, with 1 occurrences

